version: "3"
services:
  web:
    image: poom17345/hw3:part03
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
    environment:
      - redis=true

  redis:
    image: redis
    networks:
      - webnet
networks: 
  webnet: